//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booksDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime checkout_date { get; set; }
        public System.DateTime return_date { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
